COPIED_MAKEFILE := /home_new/onder/dev_in_place_content/lib_info/OpSu132_b32_deploy/types/itpp_opencv.mk
TYPE_MK := mex
FILE_MK := $(HOME)/dev_in_place/makefiles/genre/mex/makefile_in_place_mex.mk

include $(HOME)/dev_in_place/makefiles/assigner/makefile_assigner.mk
